version: "3.3"

services:
  rabbitmq:
    image: rabbitmq
    container_name: 'RMQ'
    ports:
      - 5673:5672
      - 15673:15672
    
  postgres:
    image: postgres
    container_name: 'postgres'
    ports:
     - 5432:5432
    env_file:
      - envs/.env.postgres

  redis: 
    image: redis:alpine
    container_name: 'redis'
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    volumes:
      - redis:/var/lib/redis/data
    ports: 
      - 6379:6379
    env_file: 
     - envs/.env.redis

volumes:
  redis:
